import type { Match } from "../types"

export const MOCK_MATCHES: Record<string, Match[]> = {
    "UEFA Champions League": [
        {
            id: "1",
            leagueId: "4480",
            homeTeam: { id: "1", name: "Arsenal", logo: "/assets/svgs/clubs/arsenal.svg", status: "AGO" },
            awayTeam: { id: "2", name: "Valencia", logo: "/assets/svgs/clubs/valenica.svg" },
            homeScore: 2,
            awayScore: 1,
            homeScoreHalf: 3,
            awayScoreHalf: 2,
            status: "finished",
            startTime: "2025-12-10T20:00:00",
            league: "UEFA Champions League",
        },
        {
            id: "2",
            leagueId: "4480",
            homeTeam: { id: "3", name: "Real Madrid", logo: "/assets/svgs/clubs/realmadrid.svg", hasRedCard: true },
            awayTeam: { id: "4", name: "Leicester City", logo: "/assets/svgs/clubs/leicester.svg", status: "PEN" },
            homeScore: 1,
            awayScore: 3,
            homeScoreHalf: 3,
            awayScoreHalf: 1,
            status: "finished",
            startTime: "2025-12-10T20:00:00",
            league: "UEFA Champions League",
        },
    ],
    "English Premier League": [
        {
            id: "3",
            leagueId: "4328",
            homeTeam: { id: "5", name: "Arsenal", logo: "/assets/svgs/clubs/arsenal.svg" },
            awayTeam: { id: "6", name: "Manchester City", logo: "/assets/svgs/clubs/man-city.svg" },
            homeScore: 4,
            awayScore: 1,
            status: "live",
            minute: 63,
            startTime: "2025-12-10T18:00:00",
            league: "English Premier League",
        },
        {
            id: "4",
            leagueId: "4328",
            homeTeam: { id: "7", name: "Newcastle United", logo: "/assets/svgs/clubs/newcastle.svg" },
            awayTeam: { id: "8", name: "Liverpool", logo: "/assets/svgs/clubs/liverpool.svg" },
            homeScore: 0,
            awayScore: 1,
            status: "halftime",
            startTime: "2025-12-10T19:00:00",
            league: "English Premier League",
        },
        {
            id: "5",
            leagueId: "4328",
            homeTeam: { id: "9", name: "Burnley", logo: "/assets/svgs/clubs/burnley.svg" },
            awayTeam: { id: "6", name: "Manchester City", logo: "/assets/svgs/clubs/man-city.svg" },
            status: "scheduled",
            startTime: "2025-12-10T23:00:00",
            league: "English Premier League",
        },
        {
            id: "6",
            leagueId: "4328",
            homeTeam: { id: "10", name: "Chelsea", logo: "/assets/svgs/clubs/chelsea.svg" },
            awayTeam: { id: "11", name: "Southampton", logo: "/assets/svgs/clubs/southampton.svg" },
            status: "scheduled",
            startTime: "2025-12-10T23:00:00",
            league: "English Premier League",
        },
    ],
};

export const POLLING_INTERVAL = 20000; // 20 seconds
